### ISSUE TITLE
error reading the files

### ISSUE THREAD

**Issue by hex41434** [facebookresearch/plush_dataset#3]
Hi! thanks a lot for the dataset you provided.
when I try to read npz files using the code you provided, I got an error : 
"Cannot load file containing pickled data when allow_pickle=False" 
surprisingly, when I set allow_pickle=True, then I got another error : 
"Failed to interpret file '../plush_dataset-main/dog/reconstruction/00000000.npz' as a pickle"

then I tried to read the data in other folders and had issues again. (even with torch.load for .pt files)

so, am I using incorrect python version or the uploaded files might be corrupted?

Thanks in advance,
Aida

**Comment by antonagafonov** [comment]
Same for me,
Cannot open the pickle file.

_pickle.UnpicklingError: Failed to interpret file 'baby_alien/reconstruction/00000003.npz' as a pickle

**Comment by tr-edith** [comment]
Hi,

can you please let us know which version of python, pytorch, numpy, and 
which OS you are using? And can you also please provide the lines of 
code you are using to load the files?

It works for me with python 3.7, pytorch 1.10.1, numpy 1.21.6 under 
Debian 11 when using np.load(os.path.join(FOLDER, 
"00000003.npz"))["vertices"] for the baby_alien reconstruction. Same for 
the dog 000000000.npz. The dog mask.pt works with 
torch.load(os.path.join(FOLDER, "mask.pt"))

**Comment by antonagafonov** [comment]
Hi,
Thanks for the fast reply.
It works for me now, my problem was with repository cloning. Files were corrupted.

Thanks

**Comment by hex41434** [comment]
Thanks for your reply. I tried single files, and it works (each npz file is about 1.1 Mbytes). Seems I have the same problem that lies in the way I am cloning the dataset (npz files are only a few Kbytes which shows they are corrupted). 

So, my bad! what is the correct way to download the files?

**Comment by tr-edith** [comment]
It might be necessary to install Github's Large File System extension.
That's very easy, first delete your current clone of the repo and then, in
your command line, run: "git lfs install". Then do a git clone again.
Please let me know whether that helps, such that we can update the readme
accordingly.

**Comment by hex41434** [comment]
Thanks a lot! It works on my Macbook. (using brew install git-lfs) 

Best
